window.ROADMAP_DATA = {
  project: {
    title: 'План развития Skillaz Start',
    subtitle: 'От первого входа до управляемой адаптации и внутренних переходов',
    updatedAt: '2026-09-09T12:00:00+03:00',
    owner: 'Продуктовая команда Skillaz Start',
  },
  releases: [
    {
      id: 'sep09',
      date: '2026-09-09',
      shortDate: '09.09',
      title: 'Основа MVP',
      promise: 'Кандидат начинает пребординг до выхода, а сотрудник и руководитель работают с целями адаптации.',
    },
    {
      id: 'oct07',
      date: '2026-10-07',
      shortDate: '07.10',
      title: 'Рабочие сценарии',
      promise: 'Руководитель и HR получают основные инструменты ведения адаптации и внутренних переходов.',
    },
    {
      id: 'nov05',
      date: '2026-11-05',
      shortDate: '05.11',
      title: 'Целостный Skillaz Start',
      promise: 'Единая точка входа, AI-помощник и подготовленный контур самостоятельного запуска клиента.',
    },
  ],
  lanes: [
    { id: 'entry', title: 'Старт и доступ', description: 'Быстрый запуск кандидата и нового клиента', color: '#3569c8' },
    { id: 'adaptation', title: 'Адаптация', description: 'Сценарии сотрудника, руководителя и HR', color: '#16846b' },
    { id: 'experience', title: 'Умный рабочий стол', description: 'Приоритеты, подсказки и AI-помощник', color: '#6f52b5' },
    { id: 'mobility', title: 'Внутренние переходы', description: 'Вакансии и мобильность внутри компании', color: '#c26a24' },
    { id: 'content', title: 'Методика и наполнение', description: 'Материалы, шаблоны и продуктовый контент', color: '#62707b', placeholder: true },
    { id: 'promo', title: 'Промо и активности', description: 'Коммуникации, демо и запуск на рынок', color: '#a34867', placeholder: true },
  ],
  features: [
    {
      id: 'preboarding-access', lane: 'entry', start: 1, end: 1, release: 'sep09',
      title: 'Пребординг до первого рабочего дня',
      outcome: 'Кандидат входит в план по временной ссылке без полноценной учётной записи и получает нужные уведомления.',
      status: 'done', progress: 100, owner: 'Команда адаптации',
      scope: ['Временная ссылка на план', 'Уведомление кандидата', 'Безопасное завершение доступа'],
      sources: [{ label: 'DEV-61896', url: 'https://tracker.yandex.ru/DEV-61896' }],
    },
    {
      id: 'goals-wave-one', lane: 'adaptation', start: 1, end: 1, release: 'sep09',
      title: 'Цели адаптации в индивидуальном плане',
      outcome: 'Руководитель ставит и публикует цели, сотрудник выполняет шаги, а проверяющий подтверждает результат.',
      status: 'acceptance', progress: 92, owner: 'Команда адаптации',
      scope: ['Цели и промежуточные результаты', 'Публикация руководителем', 'Прогресс и уведомления', 'Подтверждение результата'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }],
    },
    {
      id: 'manager-workspace', lane: 'adaptation', start: 2, end: 2, release: 'oct07',
      title: 'Рабочее место руководителя',
      outcome: 'Руководитель видит планы команды, свои действия и сразу открывает нужный элемент плана.',
      status: 'in_progress', progress: 55, owner: 'Команда адаптации',
      scope: ['Мои действия', 'Планы команды', 'Переход к нужному элементу', 'Приоритеты и сроки'],
      sources: [{ label: 'DEV-64603', url: 'https://tracker.yandex.ru/DEV-64603' }],
    },
    {
      id: 'admin-editor', lane: 'adaptation', start: 2, end: 2, release: 'oct07',
      title: 'Новый редактор адаптации для HR',
      outcome: 'HR собирает понятный маршрут адаптации, настраивает участников, сроки и правила работы с целями.',
      status: 'in_progress', progress: 48, owner: 'Команда адаптации',
      scope: ['Новый редактор шаблона', 'Настройка маршрута', 'Участники и сроки', 'Публикация целей'],
      sources: [{ label: 'DEV-64604', url: 'https://tracker.yandex.ru/DEV-64604' }],
    },
    {
      id: 'goal-catalog', lane: 'adaptation', start: 2, end: 2, release: 'oct07',
      title: 'Каталог типовых целей',
      outcome: 'HR повторно использует готовые цели по должности и подразделению вместо ручного создания в каждом шаблоне.',
      status: 'in_progress', progress: 38, owner: 'Команда адаптации',
      scope: ['Создание и редактирование цели', 'Категории и функции', 'Применимость к оргструктуре', 'Копирование в шаблон'],
      sources: [{ label: 'DEV-64620', url: 'https://tracker.yandex.ru/DEV-64620' }, { label: 'DEV-64661', url: 'https://tracker.yandex.ru/DEV-64661' }],
    },
    {
      id: 'checkpoints', lane: 'adaptation', start: 2, end: 3, release: 'nov05',
      title: 'Контрольные точки и риски',
      outcome: 'Руководитель проводит регулярные встречи, фиксирует риски и не теряет обязательные действия по сотруднику.',
      status: 'in_progress', progress: 32, owner: 'Команда адаптации',
      scope: ['Повестка встречи', 'Пульс сотрудника', 'Фиксация риска', 'Действия руководителя'],
      sources: [{ label: 'DEV-64608', url: 'https://tracker.yandex.ru/DEV-64608' }],
    },
    {
      id: 'final-review', lane: 'adaptation', start: 3, end: 3, release: 'nov05',
      title: 'Итоги адаптации',
      outcome: 'Руководитель и HR получают единую сводку результатов и принимают решение по завершению плана.',
      status: 'planned', progress: 12, owner: 'Команда адаптации',
      scope: ['Сводка результатов', 'Комментарий руководителя', 'Решение по завершению', 'История итогов'],
      sources: [{ label: 'DEV-64609', url: 'https://tracker.yandex.ru/DEV-64609' }],
    },
    {
      id: 'reporting', lane: 'adaptation', start: 3, end: 3, release: 'nov05',
      title: 'Отчётность по адаптации',
      outcome: 'HR видит состояние запусков, прогресс и проблемные зоны без ручной сборки отчётов.',
      status: 'planned', progress: 8, owner: 'Продуктовая аналитика',
      scope: ['Статусы планов', 'Прогресс и сроки', 'Риски', 'Выгрузка данных'],
      sources: [{ label: 'DEV-64880', url: 'https://tracker.yandex.ru/DEV-64880' }],
    },
    {
      id: 'dynamic-home', lane: 'experience', start: 2, end: 3, release: 'nov05',
      title: 'Динамическая главная',
      outcome: 'Сотрудник и руководитель начинают день с приоритетных действий из обучения, адаптации и других процессов.',
      status: 'in_progress', progress: 20, owner: 'Юлия / продукт',
      scope: ['Единая лента действий', 'Автоматические приоритеты', 'Карточки по ролям', 'Переход к объекту'],
      sources: [{ label: 'DEV-66122', url: 'https://tracker.yandex.ru/DEV-66122' }],
    },
    {
      id: 'ai-assistant', lane: 'experience', start: 2, end: 3, release: 'nov05',
      title: 'AI-помощник по адаптации',
      outcome: 'Сотрудник быстро понимает, что делать дальше, а руководитель получает сводку по команде и помощь в подготовке целей.',
      status: 'in_progress', progress: 24, owner: 'AI + LMS команды',
      scope: ['Следующие действия сотрудника', 'Сводка по плану', 'Команда, требующая внимания', 'Черновик целей с подтверждением'],
      sources: [{ label: 'DEV-64617', url: 'https://tracker.yandex.ru/DEV-64617' }, { label: 'Проектное решение', url: 'https://docs.google.com/document/d/1FiwFB8ALvGpfbfMpiVs9qy6cHAQZO2umHQk2T6sockA/edit?tab=t.0' }],
    },
    {
      id: 'tenant-copy', lane: 'entry', start: 2, end: 3, release: 'nov05',
      title: 'Быстрый запуск стенда из шаблона',
      outcome: 'Новый клиент получает готовые настройки и контент без долгой ручной конфигурации с нуля.',
      status: 'in_progress', progress: 44, owner: 'Платформенная команда',
      scope: ['Копирование базовых настроек', 'Ролевая модель и уведомления', 'Контент адаптации', 'Проверка целостности'],
      sources: [{ label: 'DEV-65423', url: 'https://tracker.yandex.ru/DEV-65423' }],
    },
    {
      id: 'self-service', lane: 'entry', start: 2, end: 3, release: 'nov05',
      title: 'Самостоятельная настройка Skillaz Start',
      outcome: 'Клиент проходит основные шаги подключения и брендирования без постоянного участия команды внедрения.',
      status: 'in_progress', progress: 18, owner: 'Платформенная команда',
      scope: ['Стартовая развилка настроек', 'Экран авторизации', 'Отправка почты', 'Базовое брендирование'],
      sources: [{ label: 'DEV-65837', url: 'https://tracker.yandex.ru/DEV-65837' }],
    },
    {
      id: 'internal-jobs-core', lane: 'mobility', start: 2, end: 2, release: 'oct07',
      title: 'Внутренняя витрина вакансий',
      outcome: 'Сотрудник видит возможности внутри компании и откликается, а HR управляет вакансиями в одном процессе с ATS.',
      status: 'in_progress', progress: 72, owner: 'Команда внутренних переходов',
      scope: ['Интеграция с ATS Skillaz и Open API', 'Витрина и карточка вакансии', 'Отклик и история откликов', 'Ручное создание и управление'],
      sources: [{ label: 'DEV-64440', url: 'https://tracker.yandex.ru/DEV-64440' }, { label: 'Роадмап команды', url: 'https://docs.google.com/spreadsheets/d/1uSGSlFyl51AdHcJwBd8zZd0onzs3DzjlnbQdO0yFRAk/edit?gid=1309037961' }],
    },
    {
      id: 'internal-jobs-alerts', lane: 'mobility', start: 3, end: 3, release: 'nov05',
      title: 'Подписки и уведомления о вакансиях',
      outcome: 'Подходящие сотрудники быстрее узнают о новых возможностях, а вакансии закрываются внутренними кандидатами.',
      status: 'planned', progress: 5, owner: 'Команда внутренних переходов',
      scope: ['Подписка по фильтрам', 'Уведомление о новой вакансии', 'Управление подпиской'],
      sources: [{ label: 'DEV-65548', url: 'https://tracker.yandex.ru/DEV-65548' }, { label: 'DEV-65550', url: 'https://tracker.yandex.ru/DEV-65550' }],
    },
  ],
  placeholders: [
    { id: 'content-slot', lane: 'content', title: 'План потока будет добавлен', text: 'Здесь появятся методические материалы, шаблоны, готовое наполнение и ответственные.' },
    { id: 'promo-slot', lane: 'promo', title: 'План потока будет добавлен', text: 'Здесь появятся промо-материалы, клиентские активности, демо и коммуникации запуска.' },
  ],
};
