window.ROADMAP_DATA = {
  project: {
    title: 'План развития Skillaz Start',
    subtitle: 'От первого входа до управляемой адаптации и внутренних переходов',
    updatedAt: '2026-09-09T12:00:00+03:00',
    owner: 'Продуктовая команда Skillaz Start',
  },
  releases: [
    {
      id: 'sep09',
      date: '2026-09-09',
      shortDate: '09.09',
      title: 'Основа MVP',
      promise: 'HR настраивает цели, руководитель публикует их, сотрудник выполняет шаги, а проверяющий принимает результат. Кандидат получает доступ к пребордингу до выхода.',
    },
    {
      id: 'oct07',
      date: '2026-10-07',
      shortDate: '07.10',
      title: 'Рабочие сценарии',
      promise: 'Руководитель и HR получают основные инструменты ведения адаптации и внутренних переходов.',
    },
    {
      id: 'nov05',
      date: '2026-11-05',
      shortDate: '05.11',
      title: 'Целостный Skillaz Start',
      promise: 'Единая точка входа, AI-помощник и подготовленный контур самостоятельного запуска клиента.',
    },
  ],
  lanes: [
    { id: 'entry', title: 'Запуск и коробка', description: 'Пребординг, пресет и самостоятельное подключение', color: '#3569c8' },
    { id: 'adaptation', title: 'Адаптация', description: 'Сценарии сотрудника, руководителя и HR', color: '#16846b' },
    { id: 'experience', title: 'Главная и AI', description: 'Приоритетные действия и AI-помощник', color: '#6f52b5' },
    { id: 'mobility', title: 'Внутренние переходы', description: 'Вакансии и мобильность внутри компании', color: '#c26a24' },
    { id: 'content', title: 'Методика и наполнение', description: 'Материалы, шаблоны и продуктовый контент', color: '#62707b', placeholder: true },
    { id: 'promo', title: 'Промо и активности', description: 'Коммуникации, демо и запуск на рынок', color: '#a34867', placeholder: true },
  ],
  features: [
    {
      id: 'preboarding-access', lane: 'entry', start: 1, end: 1, release: 'sep09',
      title: 'Пребординг до первого рабочего дня',
      outcome: 'Кандидат входит в план по временной ссылке без полноценной учётной записи и получает нужные уведомления.',
      status: 'done', progress: 100, owner: 'Команда адаптации',
      scope: ['Временная ссылка на план', 'Уведомление кандидата', 'Безопасное завершение доступа'],
      sources: [{ label: 'DEV-61896', url: 'https://tracker.yandex.ru/DEV-61896' }],
    },
    {
      id: 'goal-template-setup', lane: 'adaptation', start: 1, end: 1, release: 'sep09',
      title: 'Настройка целей в шаблоне',
      outcome: 'HR создаёт цели и шаги в шаблоне адаптации, задаёт сроки и переносит готовую структуру в индивидуальный план.',
      status: 'acceptance', progress: 92, owner: 'Команда адаптации',
      scope: ['Создание цели и шагов в шаблоне', 'Название, ожидаемый результат и сроки', 'Копирование в индивидуальный план', 'Настройка доступности блока целей'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }, { label: 'DEV-62955', url: 'https://tracker.yandex.ru/DEV-62955' }],
    },
    {
      id: 'goal-manager-publish', lane: 'adaptation', start: 1, end: 1, release: 'sep09',
      title: 'Создание и публикация целей руководителем',
      outcome: 'Руководитель уточняет цели сотрудника в плане и публикует их, когда набор готов к работе.',
      status: 'acceptance', progress: 90, owner: 'Команда адаптации',
      scope: ['Создание и редактирование целей в плане', 'Назначение шагов сотруднику', 'Публикация набора целей', 'Контроль срока постановки целей'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }, { label: 'DEV-62961', url: 'https://tracker.yandex.ru/DEV-62961' }, { label: 'DEV-65241', url: 'https://tracker.yandex.ru/DEV-65241' }],
    },
    {
      id: 'goal-employee-flow', lane: 'adaptation', start: 1, end: 1, release: 'sep09',
      title: 'Работа сотрудника с целями и шагами',
      outcome: 'Сотрудник видит опубликованные цели, выполняет шаги и отправляет полученный результат на подтверждение.',
      status: 'acceptance', progress: 90, owner: 'Команда адаптации',
      scope: ['Цели в плане сотрудника', 'Статусы цели и шага', 'Комментарий к результату', 'Отправка шага на подтверждение'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }, { label: 'DEV-64395', url: 'https://tracker.yandex.ru/DEV-64395' }, { label: 'DEV-64629', url: 'https://tracker.yandex.ru/DEV-64629' }],
    },
    {
      id: 'goal-review-flow', lane: 'adaptation', start: 1, end: 1, release: 'sep09',
      title: 'Проверка результата по шагу',
      outcome: 'Назначенный проверяющий принимает результат сотрудника или возвращает шаг на доработку с понятной обратной связью.',
      status: 'acceptance', progress: 90, owner: 'Команда адаптации',
      scope: ['Назначение проверяющего', 'Подтверждение выполнения', 'Возврат на доработку', 'Уведомления участникам'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }, { label: 'DEV-64630', url: 'https://tracker.yandex.ru/DEV-64630' }, { label: 'DEV-64632', url: 'https://tracker.yandex.ru/DEV-64632' }],
    },
    {
      id: 'goal-progress', lane: 'adaptation', start: 1, end: 1, release: 'sep09',
      title: 'Прогресс и статусы целей',
      outcome: 'Участники видят состояние целей и шагов, а прогресс целей становится основным показателем прохождения плана.',
      status: 'acceptance', progress: 91, owner: 'Команда адаптации',
      scope: ['Расчёт прогресса цели', 'Прогресс плана по целям', 'Ограничение действий по статусам', 'Уведомления об изменениях'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }, { label: 'DEV-62377', url: 'https://tracker.yandex.ru/DEV-62377' }, { label: 'DEV-62945', url: 'https://tracker.yandex.ru/DEV-62945' }],
    },
    {
      id: 'manager-workspace', lane: 'adaptation', start: 2, end: 2, release: 'oct07',
      title: 'Редизайн «Моя команда → Адаптация»',
      outcome: 'Руководитель работает с планами команды и своими действиями в обновлённом разделе адаптации.',
      status: 'planned', progress: 10, owner: 'Команда адаптации',
      scope: ['Новая навигация раздела', 'Список и карточка планов', 'Экран «Мои действия»', 'Контекст руководителя и помощника', 'Адаптивный интерфейс'],
      sources: [{ label: 'DEV-64603', url: 'https://tracker.yandex.ru/DEV-64603' }],
    },
    {
      id: 'admin-editor', lane: 'adaptation', start: 2, end: 2, release: 'oct07',
      title: 'Редизайн редактора адаптации',
      outcome: 'HR настраивает шаблоны и индивидуальные планы в обновлённом интерфейсе редактора адаптации.',
      status: 'planned', progress: 5, owner: 'Команда адаптации',
      scope: ['Разделение административных страниц', 'Редизайн списка планов', 'Справочники адаптации', 'Фильтры и группировки', 'Настройка столбцов и массовые действия'],
      sources: [{ label: 'DEV-64604', url: 'https://tracker.yandex.ru/DEV-64604' }],
    },
    {
      id: 'goal-catalog', lane: 'adaptation', start: 2, end: 2, release: 'oct07',
      title: 'Шаблоны и каталог целей',
      outcome: 'HR задаёт способ формирования целей и повторно использует готовые цели по должности и подразделению.',
      status: 'planned', progress: 10, owner: 'Команда адаптации',
      scope: ['Цели полностью от руководителя', 'Готовые цели из шаблона', 'Финализация шаблонных целей руководителем', 'Каталог и применимость целей', 'Копирование цели в шаблон'],
      sources: [{ label: 'DEV-64620', url: 'https://tracker.yandex.ru/DEV-64620' }, { label: 'DEV-64661', url: 'https://tracker.yandex.ru/DEV-64661' }],
    },
    {
      id: 'checkpoints', lane: 'adaptation', start: 2, end: 3, release: 'nov05',
      title: 'Контрольные точки и риски',
      outcome: 'Руководитель проводит регулярные встречи, фиксирует риски и не теряет обязательные действия по сотруднику.',
      status: 'in_progress', progress: 10, owner: 'Команда адаптации',
      scope: ['Настройка контрольных точек HR', 'Пульс сотрудника', 'Статусы и просрочка', 'Автоматический и ручной риск', 'Мониторинг и уведомления'],
      sources: [{ label: 'DEV-64608', url: 'https://tracker.yandex.ru/DEV-64608' }],
    },
    {
      id: 'final-review', lane: 'adaptation', start: 3, end: 3, release: 'nov05',
      title: 'Финальное ревью и сводка результатов',
      outcome: 'Руководитель получает единую сводку и принимает решение: завершить план, признать результат неуспешным или вернуть план в работу.',
      status: 'in_progress', progress: 8, owner: 'Команда адаптации',
      scope: ['Обязательное согласование планов с целями', 'Ранняя отправка на ревью', 'Финальная сводка', 'Три решения руководителя', 'Уведомления HR и автора плана'],
      sources: [{ label: 'DEV-64609', url: 'https://tracker.yandex.ru/DEV-64609' }],
    },
    {
      id: 'reporting', lane: 'adaptation', start: 3, end: 3, release: 'nov05',
      title: 'Отчётность по адаптации',
      outcome: 'HR видит состояние запусков, прогресс и проблемные зоны без ручной сборки отчётов.',
      status: 'planned', progress: 0, owner: 'Продуктовая аналитика',
      scope: ['Статусы планов', 'Прогресс и сроки', 'Риски', 'Выгрузка данных'],
      sources: [{ label: 'DEV-64880', url: 'https://tracker.yandex.ru/DEV-64880' }],
    },
    {
      id: 'dynamic-home', lane: 'experience', start: 2, end: 3, release: 'nov05',
      title: 'Динамическая главная: приоритетные действия',
      outcome: 'Сотрудник и руководитель начинают день с приоритетных действий из обучения, адаптации и других процессов.',
      status: 'in_progress', progress: 10, owner: 'Юлия / продукт',
      scope: ['Курсы и программы обучения', 'Планы, задачи и контрольные точки адаптации', 'Автоматический порядок по срокам и важности', 'Переход к исходному объекту'],
      sources: [{ label: 'DEV-66122', url: 'https://tracker.yandex.ru/DEV-66122' }],
    },
    {
      id: 'ai-assistant', lane: 'experience', start: 2, end: 3, release: 'nov05',
      title: 'AI-помощник по адаптации',
      outcome: 'Сотрудник быстро понимает, что делать дальше, а руководитель получает сводку по команде и помощь в подготовке целей.',
      status: 'in_progress', progress: 10, owner: 'AI + LMS команды',
      scope: ['Следующие действия сотрудника', 'Сводка по плану', 'Команда, требующая внимания', 'Черновик целей с подтверждением'],
      sources: [{ label: 'DEV-64617', url: 'https://tracker.yandex.ru/DEV-64617' }, { label: 'Проектное решение', url: 'https://docs.google.com/document/d/1FiwFB8ALvGpfbfMpiVs9qy6cHAQZO2umHQk2T6sockA/edit?tab=t.0' }],
    },
    {
      id: 'tenant-copy', lane: 'entry', start: 2, end: 3, release: 'nov05',
      title: 'Пресет коробки: копирование tenant',
      outcome: 'Суперадминистратор создаёт новый клиентский tenant на основе эталонного пресета с готовыми настройками и контентом.',
      status: 'in_progress', progress: 35, owner: 'Платформенная команда',
      scope: ['Выбор пустого tenant или tenant-источника', 'Разрешённый источник копирования', 'Независимые копии настроек и сущностей', 'Восстановление связей внутри нового tenant'],
      sources: [{ label: 'DEV-65423', url: 'https://tracker.yandex.ru/DEV-65423' }],
    },
    {
      id: 'self-service', lane: 'entry', start: 2, end: 3, release: 'nov05',
      title: 'Start Self-Service: настройка коробки',
      outcome: 'Клиент проходит основные шаги подключения и брендирования без постоянного участия команды внедрения.',
      status: 'planned', progress: 5, owner: 'Платформенная команда',
      scope: ['Стартовая развилка настроек', 'Экран авторизации', 'Отправка почты', 'Базовое брендирование'],
      sources: [{ label: 'DEV-65837', url: 'https://tracker.yandex.ru/DEV-65837' }],
    },
    {
      id: 'internal-jobs-core', lane: 'mobility', start: 2, end: 2, release: 'oct07',
      title: 'Внутренняя витрина вакансий',
      outcome: 'Сотрудник видит возможности внутри компании и откликается, а HR управляет вакансиями в одном процессе с ATS.',
      status: 'in_progress', progress: 72, owner: 'Команда внутренних переходов',
      scope: ['Интеграция с ATS Skillaz и Open API', 'Витрина и карточка вакансии', 'Отклик и история откликов', 'Ручное создание и управление'],
      sources: [{ label: 'DEV-64440', url: 'https://tracker.yandex.ru/DEV-64440' }, { label: 'Роадмап команды', url: 'https://docs.google.com/spreadsheets/d/1uSGSlFyl51AdHcJwBd8zZd0onzs3DzjlnbQdO0yFRAk/edit?gid=1309037961' }],
    },
    {
      id: 'internal-jobs-alerts', lane: 'mobility', start: 3, end: 3, release: 'nov05',
      title: 'Подписки и уведомления о вакансиях',
      outcome: 'Подходящие сотрудники быстрее узнают о новых возможностях, а вакансии закрываются внутренними кандидатами.',
      status: 'planned', progress: 5, owner: 'Команда внутренних переходов',
      scope: ['Подписка по фильтрам', 'Уведомление о новой вакансии', 'Управление подпиской'],
      sources: [{ label: 'DEV-65548', url: 'https://tracker.yandex.ru/DEV-65548' }, { label: 'DEV-65550', url: 'https://tracker.yandex.ru/DEV-65550' }],
    },
  ],
  placeholders: [
    { id: 'content-slot', lane: 'content', title: 'План потока будет добавлен', text: 'Здесь появятся методические материалы, шаблоны, готовое наполнение и ответственные.' },
    { id: 'promo-slot', lane: 'promo', title: 'План потока будет добавлен', text: 'Здесь появятся промо-материалы, клиентские активности, демо и коммуникации запуска.' },
  ],
};
