window.ROADMAP_DATA = {
  project: {
    title: 'План проекта Skillaz Start',
    subtitle: 'Что разрабатываем между релизами и какую ценность получает пользователь на каждой контрольной дате',
    updatedAt: '2026-09-11T17:05:00+03:00',
    owner: 'Продуктовая команда Skillaz Start',
  },
  releases: [
    {
      id: 'sep09', date: '2026-09-09', shortDate: '09.09', version: 'Релиз 0.78',
      development: 'Разработка до 09.09', title: 'Цели адаптации и внутренние вакансии',
      promise: 'Кандидат входит в пребординг по временной ссылке, участники работают с целями и промежуточными результатами, а сотрудники видят внутренние вакансии и откликаются на них.',
    },
    {
      id: 'oct07', date: '2026-10-07', shortDate: '07.10', version: 'Релиз 0.79',
      development: 'Разработка 10.09 - 07.10', title: 'Рабочие места, каталог и внутренняя мобильность',
      promise: 'Руководитель и HR получают обновленные рабочие разделы и самостоятельный каталог целей; появляются базовые контрольные точки и отчетность, а внутренняя витрина дополняется ручным созданием вакансий и ролевыми доступами.',
    },
    {
      id: 'nov05', date: '2026-11-05', shortDate: '05.11', version: 'Релиз 0.80',
      development: 'Разработка 08.10 - 05.11', title: 'Целостный Skillaz Start',
      promise: 'Каталог целей подключается к шаблонам и планам, HR получает инструменты управления списком планов, контрольные точки и риски работают сквозным процессом, а клиент получает AI-помощника и контур самостоятельной настройки коробки.',
    },
  ],
  lanes: [
    { id: 'entry', title: 'Запуск и коробка', description: 'Пребординг, пресет и самостоятельное подключение', color: '#3569c8' },
    { id: 'adaptation', title: 'Адаптация', description: 'Сценарии сотрудника, руководителя и HR', color: '#16846b' },
    { id: 'experience', title: 'Главная и AI', description: 'Приоритетные действия и AI-помощник', color: '#6f52b5' },
    { id: 'mobility', title: 'Внутренние переходы', description: 'Вакансии и мобильность внутри компании', color: '#c26a24' },
    { id: 'content', title: 'Методика и наполнение', description: 'Материалы, шаблоны и продуктовый контент', color: '#62707b', placeholder: true },
    { id: 'promo', title: 'Промо и активности', description: 'Коммуникации, демо и запуск на рынок', color: '#a34867', placeholder: true },
  ],
  features: [
    {
      id: 'preboarding-access', lane: 'entry', release: 'sep09', title: 'Пребординг до первого рабочего дня',
      outcome: 'Кандидат получает персональную временную ссылку и сразу открывает назначенный план без ввода логина и пароля.',
      status: 'done', progress: 100, owner: 'Команда адаптации',
      scope: ['Временная ссылка на конкретный план', 'Ограниченная сессия кандидата', 'Welcome-уведомление со ссылкой', 'Безопасная инвалидация доступа'],
      sources: [{ label: 'DEV-61896', url: 'https://tracker.yandex.ru/DEV-61896' }],
    },
    {
      id: 'goal-block-settings', lane: 'adaptation', release: 'sep09', title: 'Настройка блока целей в шаблоне',
      outcome: 'HR включает блок целей и определяет срок, к которому руководитель должен опубликовать цели сотруднику.',
      status: 'done', progress: 100, owner: 'Команда адаптации',
      scope: ['Включение блока «Цели адаптации»', 'Срок публикации целей руководителем', 'Правила доступности блока в индивидуальном плане'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }, { label: 'DEV-62955', url: 'https://tracker.yandex.ru/DEV-62955' }],
    },
    {
      id: 'goal-authoring', lane: 'adaptation', release: 'sep09', title: 'Создание и публикация целей',
      outcome: 'HR создает цели в шаблоне или плане, а руководитель при необходимости уточняет набор и публикует его сотруднику.',
      status: 'done', progress: 100, owner: 'Команда адаптации',
      scope: ['Создание и редактирование целей HR', 'Создание и редактирование целей руководителем', 'Публикация целей сотруднику', 'Контроль срока постановки целей'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }, { label: 'DEV-62961', url: 'https://tracker.yandex.ru/DEV-62961' }, { label: 'DEV-63133', url: 'https://tracker.yandex.ru/DEV-63133' }, { label: 'DEV-65241', url: 'https://tracker.yandex.ru/DEV-65241' }],
    },
    {
      id: 'goal-employee-flow', lane: 'adaptation', release: 'sep09', title: 'Работа сотрудника с целями и промежуточными результатами',
      outcome: 'Сотрудник видит опубликованные цели, фиксирует промежуточный результат и отправляет его на подтверждение.',
      status: 'done', progress: 100, owner: 'Команда адаптации',
      scope: ['Цели в плане сотрудника', 'Статусы цели и промежуточного результата', 'Комментарий к результату', 'Отправка результата на подтверждение'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }, { label: 'DEV-64395', url: 'https://tracker.yandex.ru/DEV-64395' }, { label: 'DEV-64629', url: 'https://tracker.yandex.ru/DEV-64629' }, { label: 'DEV-64988', url: 'https://tracker.yandex.ru/DEV-64988' }],
    },
    {
      id: 'goal-review-flow', lane: 'adaptation', release: 'sep09', title: 'Проверка промежуточного результата',
      outcome: 'Назначенный проверяющий подтверждает результат сотрудника или возвращает его на доработку с обратной связью.',
      status: 'done', progress: 100, owner: 'Команда адаптации',
      scope: ['Назначение проверяющего', 'Подтверждение результата', 'Возврат на доработку', 'Фиксация невыполнения'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }, { label: 'DEV-64630', url: 'https://tracker.yandex.ru/DEV-64630' }],
    },
    {
      id: 'goal-progress', lane: 'adaptation', release: 'sep09', title: 'Статусы и прогресс целей',
      outcome: 'Участники видят состояние целей и промежуточных результатов, а прогресс целей становится основным показателем плана.',
      status: 'done', progress: 100, owner: 'Команда адаптации',
      scope: ['Расчет прогресса цели', 'Прогресс плана по целям', 'Статусы целей и результатов', 'Ограничение действий по ролям и статусам'],
      sources: [{ label: 'DEV-62032', url: 'https://tracker.yandex.ru/DEV-62032' }, { label: 'DEV-62377', url: 'https://tracker.yandex.ru/DEV-62377' }, { label: 'DEV-62945', url: 'https://tracker.yandex.ru/DEV-62945' }],
    },
    {
      id: 'goal-notifications', lane: 'adaptation', release: 'sep09', title: 'Уведомления по целям и результатам',
      outcome: 'Руководитель, сотрудник и проверяющий вовремя узнают о публикации целей и действиях с промежуточными результатами.',
      status: 'done', progress: 100, owner: 'Команда адаптации',
      scope: ['Напоминание руководителю о постановке целей', 'Уведомление сотруднику о публикации целей', 'Уведомление проверяющему о новом результате', 'Подтверждение или возврат результата сотруднику'],
      sources: [{ label: 'DEV-62956', url: 'https://tracker.yandex.ru/DEV-62956' }, { label: 'DEV-64631', url: 'https://tracker.yandex.ru/DEV-64631' }, { label: 'DEV-64632', url: 'https://tracker.yandex.ru/DEV-64632' }, { label: 'DEV-64633', url: 'https://tracker.yandex.ru/DEV-64633' }, { label: 'DEV-64634', url: 'https://tracker.yandex.ru/DEV-64634' }],
    },
    {
      id: 'manager-workspace', lane: 'adaptation', release: 'oct07', title: 'Редизайн рабочего места руководителя',
      outcome: 'Руководитель работает с планами команды и своими задачами в одном обновленном разделе.',
      status: 'in_progress', progress: 18, owner: 'Команда адаптации',
      scope: ['Экран «Мои действия»', 'Список и карточка планов', 'Контекст «Я руководитель / Я помощник»', 'Навигация между рабочими представлениями'],
      sources: [{ label: 'DEV-64603', url: 'https://tracker.yandex.ru/DEV-64603' }, { label: 'DEV-64676', url: 'https://tracker.yandex.ru/DEV-64676' }, { label: 'DEV-64677', url: 'https://tracker.yandex.ru/DEV-64677' }, { label: 'DEV-64678', url: 'https://tracker.yandex.ru/DEV-64678' }],
    },
    {
      id: 'manager-goal-actions', lane: 'adaptation', release: 'oct07', title: 'Действия руководителя по целям и результатам',
      outcome: 'Руководитель сразу видит, где нужно создать цели, а проверяющий — подтвердить результат сотрудника, и переходит прямо к нужному объекту плана.',
      status: 'planned', progress: 0, owner: 'Команда адаптации',
      scope: ['Действия «Создать цели» и «Подтвердить результат»', 'Группировка и фильтр по типу действия', 'Индикаторы действий над списком планов', 'Прогресс целей в карточке плана', 'Переход к нужной цели или промежуточному результату'],
      sources: [{ label: 'DEV-64679', url: 'https://tracker.yandex.ru/DEV-64679' }],
    },
    {
      id: 'admin-editor', lane: 'adaptation', release: 'sep09', title: 'Редизайн редактора и экрана планов',
      outcome: 'HR работает с шаблонами, очередью назначения, справочниками и планами сотрудников в обновленных административных разделах.',
      status: 'done', progress: 100, owner: 'Команда адаптации',
      scope: ['Разделение административных страниц', 'Редизайн очереди назначения', 'Редизайн списка планов', 'Переключение назначенных планов и черновиков', 'Справочники адаптации', 'Базовый поиск и фильтры'],
      sources: [{ label: 'DEV-64604', url: 'https://tracker.yandex.ru/DEV-64604' }],
    },
    {
      id: 'goal-template-copy', lane: 'adaptation', release: 'oct07', title: 'Цели из шаблона в плане сотрудника',
      outcome: 'HR создает цели и промежуточные результаты в шаблоне, а при назначении они копируются в индивидуальный план.',
      status: 'planned', progress: 0, owner: 'Команда адаптации',
      scope: ['Цели и промежуточные результаты в шаблоне', 'Копирование в индивидуальный план', 'Сотрудник как исполнитель результата', 'Руководитель как проверяющий по умолчанию', 'Публикация руководителем только при включенной настройке'],
      sources: [{ label: 'DEV-64620', url: 'https://tracker.yandex.ru/DEV-64620' }, { label: 'DEV-64659', url: 'https://tracker.yandex.ru/DEV-64659' }],
    },
    {
      id: 'goal-catalog', lane: 'adaptation', release: 'oct07', title: 'Каталог целей адаптации',
      outcome: 'HR ведет единый справочник типовых целей и поддерживает его актуальность для последующего переиспользования.',
      status: 'planned', progress: 0, owner: 'Команда адаптации',
      scope: ['Создание и редактирование целей HR', 'Категории и функции', 'Должность и подразделение', 'Промежуточные результаты', 'Поиск, фильтры и пагинация', 'Дублирование, архивация, восстановление и удаление'],
      sources: [{ label: 'DEV-64661', url: 'https://tracker.yandex.ru/DEV-64661' }],
    },
    {
      id: 'goal-catalog-usage', lane: 'adaptation', release: 'nov05', title: 'Цели из каталога в шаблоне и плане',
      outcome: 'HR выбирает готовые цели из каталога и добавляет их в шаблон адаптации или индивидуальный план сотрудника.',
      status: 'planned', progress: 0, owner: 'Команда адаптации',
      scope: ['Выбор цели из каталога', 'Добавление в шаблон адаптации', 'Добавление в индивидуальный план', 'Фильтрация целей по данным сотрудника', 'Создание независимой копии цели', 'Назначение исполнителя и проверяющего в плане'],
      sources: [{ label: 'DEV-64663', url: 'https://tracker.yandex.ru/DEV-64663' }],
    },
    {
      id: 'admin-plan-list-tools', lane: 'adaptation', release: 'nov05', title: 'Настройка и массовая работа со списком планов',
      outcome: 'HR настраивает представление списка планов и выполняет одинаковые действия сразу для нескольких сотрудников.',
      status: 'planned', progress: 0, owner: 'Команда адаптации',
      scope: ['Группировка списка планов', 'Настройка отображаемых столбцов', 'Базовые массовые действия', 'Сохранение выбранного представления'],
      sources: [{ label: 'DEV-64604', url: 'https://tracker.yandex.ru/DEV-64604' }, { label: 'DEV-64764', url: 'https://tracker.yandex.ru/DEV-64764' }, { label: 'DEV-64765', url: 'https://tracker.yandex.ru/DEV-64765' }, { label: 'DEV-64766', url: 'https://tracker.yandex.ru/DEV-64766' }],
    },
    {
      id: 'checkpoint-foundation', lane: 'adaptation', release: 'oct07', title: 'Контрольные точки для HR и сотрудника',
      outcome: 'HR настраивает контрольные точки, а сотрудник видит повестку и проходит доступную точку в своем плане.',
      status: 'in_progress', progress: 16, owner: 'Команда адаптации',
      scope: ['Включение контрольных точек', 'Ролевая модель', 'Создание и редактирование HR', 'Копирование из шаблона', 'Прохождение сотрудником'],
      sources: [{ label: 'DEV-64608', url: 'https://tracker.yandex.ru/DEV-64608' }, { label: 'DEV-65559', url: 'https://tracker.yandex.ru/DEV-65559' }, { label: 'DEV-65404', url: 'https://tracker.yandex.ru/DEV-65404' }, { label: 'DEV-64637', url: 'https://tracker.yandex.ru/DEV-64637' }, { label: 'DEV-64638', url: 'https://tracker.yandex.ru/DEV-64638' }, { label: 'DEV-64640', url: 'https://tracker.yandex.ru/DEV-64640' }],
    },
    {
      id: 'goal-reporting', lane: 'adaptation', release: 'oct07', title: 'Отчетность по целям и планам',
      outcome: 'HR получает выгрузки по целям, промежуточным результатам и планам сотрудников без ручной сборки данных.',
      status: 'planned', progress: 5, owner: 'Продуктовая аналитика',
      scope: ['Excel-отчет по целям и результатам', 'Выгрузка планов сотрудников', 'Статусы, сроки и прогресс'],
      sources: [{ label: 'DEV-64880', url: 'https://tracker.yandex.ru/DEV-64880' }, { label: 'DEV-64800', url: 'https://tracker.yandex.ru/DEV-64800' }, { label: 'DEV-64834', url: 'https://tracker.yandex.ru/DEV-64834' }],
    },
    {
      id: 'internal-jobs-ats', lane: 'mobility', release: 'sep09', title: 'Интеграция с ATS Skillaz',
      outcome: 'Вакансии из ATS публикуются на внутреннем карьерном сайте, а рекрутер получает внутренние отклики в привычной системе без двойной работы.',
      status: 'done', progress: 100, owner: 'Команда внутренних переходов',
      scope: ['Публикация вакансий из ATS Skillaz', 'Передача вакансий во внутреннюю витрину', 'Сбор откликов сотрудников', 'Передача внутренних откликов в ATS'],
      sources: [{ label: 'DEV-64440', url: 'https://tracker.yandex.ru/DEV-64440' }, { label: 'Роадмап команды', url: 'https://docs.google.com/spreadsheets/d/1uSGSlFyl51AdHcJwBd8zZd0onzs3DzjlnbQdO0yFRAk/edit?gid=1309037961' }],
    },
    {
      id: 'internal-jobs-open-api', lane: 'mobility', release: 'sep09', title: 'Open API для интеграции с любой ATS',
      outcome: 'Клиент может подключить витрину вакансий к своей ATS, даже если использует не Skillaz.',
      status: 'done', progress: 100, owner: 'Команда внутренних переходов',
      scope: ['Открытый API обмена вакансиями', 'Подключение внешней ATS', 'Передача данных для внутренней витрины'],
      sources: [{ label: 'DEV-64440', url: 'https://tracker.yandex.ru/DEV-64440' }, { label: 'Роадмап команды', url: 'https://docs.google.com/spreadsheets/d/1uSGSlFyl51AdHcJwBd8zZd0onzs3DzjlnbQdO0yFRAk/edit?gid=1309037961' }],
    },
    {
      id: 'internal-jobs-showcase', lane: 'mobility', release: 'sep09', title: 'Витрина вакансий для сотрудника',
      outcome: 'Сотрудник видит доступные карьерные возможности внутри компании и понимает, куда может перейти для дальнейшего роста.',
      status: 'done', progress: 100, owner: 'Команда внутренних переходов',
      scope: ['Список внутренних вакансий', 'Карточка вакансии', 'Поиск и навигация по витрине', 'Переход к отклику'],
      sources: [{ label: 'DEV-64440', url: 'https://tracker.yandex.ru/DEV-64440' }, { label: 'Роадмап команды', url: 'https://docs.google.com/spreadsheets/d/1uSGSlFyl51AdHcJwBd8zZd0onzs3DzjlnbQdO0yFRAk/edit?gid=1309037961' }],
    },
    {
      id: 'internal-jobs-applications', lane: 'mobility', release: 'sep09', title: 'Отклик и страница «Мои отклики»',
      outcome: 'Отклик заполняется кадровыми и контактными данными из профиля, а сотрудник видит историю отправленных откликов.',
      status: 'done', progress: 100, owner: 'Команда внутренних переходов',
      scope: ['Кадровые и контактные данные', 'Мотивационное письмо и резюме', 'Автозаполнение из профиля', 'История откликов сотрудника'],
      sources: [{ label: 'DEV-64440', url: 'https://tracker.yandex.ru/DEV-64440' }, { label: 'Роадмап команды', url: 'https://docs.google.com/spreadsheets/d/1uSGSlFyl51AdHcJwBd8zZd0onzs3DzjlnbQdO0yFRAk/edit?gid=1309037961' }],
    },
    {
      id: 'internal-jobs-admin', lane: 'mobility', release: 'sep09', title: 'Управление вакансиями для HR',
      outcome: 'HR быстро управляет видимостью вакансий во внутренней витрине и выгружает отклики для дальнейшей работы.',
      status: 'done', progress: 100, owner: 'Команда внутренних переходов',
      scope: ['Управление видимостью вакансий', 'Администрирование витрины', 'Выгрузка откликов в Excel'],
      sources: [{ label: 'DEV-64440', url: 'https://tracker.yandex.ru/DEV-64440' }, { label: 'Роадмап команды', url: 'https://docs.google.com/spreadsheets/d/1uSGSlFyl51AdHcJwBd8zZd0onzs3DzjlnbQdO0yFRAk/edit?gid=1309037961' }],
    },
    {
      id: 'internal-jobs-manual', lane: 'mobility', release: 'oct07', title: 'Создание вакансии вручную',
      outcome: 'Клиент без ATS может завести вакансию руками и собирать отклики в витрине; HR также может открыть вакансию только для внутренних переходов.',
      status: 'in_progress', progress: 65, owner: 'Команда внутренних переходов',
      scope: ['Ручное создание вакансии', 'Сбор откликов без ATS', 'Вакансия только для внутренних кандидатов'],
      sources: [{ label: 'DEV-64440', url: 'https://tracker.yandex.ru/DEV-64440' }, { label: 'Роадмап команды', url: 'https://docs.google.com/spreadsheets/d/1uSGSlFyl51AdHcJwBd8zZd0onzs3DzjlnbQdO0yFRAk/edit?gid=1309037961' }],
    },
    {
      id: 'internal-jobs-design', lane: 'mobility', release: 'oct07', title: 'Финальный дизайн и ревью экранов',
      outcome: 'Понятный интерфейс и последовательные шаги отклика повышают конверсию сотрудников во внутренние вакансии.',
      status: 'in_progress', progress: 70, owner: 'Команда внутренних переходов',
      scope: ['Финальный дизайн всех экранов', 'Ревью пользовательских сценариев', 'Улучшение шагов отправки отклика'],
      sources: [{ label: 'DEV-64440', url: 'https://tracker.yandex.ru/DEV-64440' }, { label: 'Роадмап команды', url: 'https://docs.google.com/spreadsheets/d/1uSGSlFyl51AdHcJwBd8zZd0onzs3DzjlnbQdO0yFRAk/edit?gid=1309037961' }],
    },
    {
      id: 'internal-jobs-access', lane: 'mobility', release: 'oct07', title: 'Права и доступы к витрине',
      outcome: 'Клиент включает раздел для нужных пользователей и регулирует видимость данных для разных ролей.',
      status: 'in_progress', progress: 55, owner: 'Команда внутренних переходов',
      scope: ['Права для пользовательских ролей', 'Включение раздела новому клиенту', 'Ограничение видимости данных'],
      sources: [{ label: 'DEV-64440', url: 'https://tracker.yandex.ru/DEV-64440' }, { label: 'Роадмап команды', url: 'https://docs.google.com/spreadsheets/d/1uSGSlFyl51AdHcJwBd8zZd0onzs3DzjlnbQdO0yFRAk/edit?gid=1309037961' }],
    },
    {
      id: 'checkpoint-management', lane: 'adaptation', release: 'nov05', title: 'Контрольные точки и риски для руководителя и HR',
      outcome: 'Руководитель проводит встречи и фиксирует риск, а HR видит единое состояние контрольных точек и рисков по планам.',
      status: 'in_progress', progress: 10, owner: 'Команда адаптации',
      scope: ['Редактирование и проведение точки руководителем', 'Пульс сотрудника', 'Автоматический и ручной риск', 'Действия руководителя', 'Риски и точки в списке HR'],
      sources: [{ label: 'DEV-64608', url: 'https://tracker.yandex.ru/DEV-64608' }, { label: 'DEV-65106', url: 'https://tracker.yandex.ru/DEV-65106' }, { label: 'DEV-64643', url: 'https://tracker.yandex.ru/DEV-64643' }, { label: 'DEV-64645', url: 'https://tracker.yandex.ru/DEV-64645' }, { label: 'DEV-64647', url: 'https://tracker.yandex.ru/DEV-64647' }, { label: 'DEV-64644', url: 'https://tracker.yandex.ru/DEV-64644' }],
    },
    {
      id: 'checkpoint-notifications', lane: 'adaptation', release: 'nov05', title: 'Уведомления по контрольным точкам',
      outcome: 'Сотрудник и ответственный получают напоминания в нужный момент и не пропускают заполнение или проведение встречи.',
      status: 'planned', progress: 0, owner: 'Команда адаптации',
      scope: ['Приближение контрольной точки', 'Необходимость заполнить контрольную точку', 'Просроченная контрольная точка', 'Переход из уведомления в нужный план'],
      sources: [{ label: 'DEV-64649', url: 'https://tracker.yandex.ru/DEV-64649' }, { label: 'DEV-64650', url: 'https://tracker.yandex.ru/DEV-64650' }, { label: 'DEV-64651', url: 'https://tracker.yandex.ru/DEV-64651' }],
    },
    {
      id: 'final-review', lane: 'adaptation', release: 'nov05', title: 'Финальное ревью и сводка результатов',
      outcome: 'Руководитель получает сводку и принимает решение: завершить план, признать результат неуспешным или вернуть план в работу.',
      status: 'in_progress', progress: 8, owner: 'Команда адаптации',
      scope: ['Обязательное согласование планов с целями', 'Ранняя отправка на ревью', 'Финальная сводка', 'Три решения руководителя', 'Уведомления автору плана и HRBP о решении'],
      sources: [{ label: 'DEV-64609', url: 'https://tracker.yandex.ru/DEV-64609' }, { label: 'DEV-65042', url: 'https://tracker.yandex.ru/DEV-65042' }, { label: 'DEV-65043', url: 'https://tracker.yandex.ru/DEV-65043' }, { label: 'DEV-65044', url: 'https://tracker.yandex.ru/DEV-65044' }],
    },
    {
      id: 'checkpoint-reporting', lane: 'adaptation', release: 'nov05', title: 'Отчетность по контрольным точкам и рискам',
      outcome: 'HR выгружает результаты контрольных точек и причины риска для анализа качества адаптации.',
      status: 'planned', progress: 0, owner: 'Продуктовая аналитика',
      scope: ['Excel-отчет по контрольным точкам', 'Excel-отчет по рискам', 'Даты, результаты и причины риска'],
      sources: [{ label: 'DEV-64880', url: 'https://tracker.yandex.ru/DEV-64880' }, { label: 'DEV-64802', url: 'https://tracker.yandex.ru/DEV-64802' }, { label: 'DEV-64803', url: 'https://tracker.yandex.ru/DEV-64803' }],
    },
    {
      id: 'dynamic-home', lane: 'experience', release: 'nov05', title: 'Динамическая главная: приоритетные действия',
      outcome: 'Сотрудник и руководитель начинают день с приоритетных действий из обучения, адаптации и других процессов.',
      status: 'in_progress', progress: 10, owner: 'Юлия / продукт',
      scope: ['Курсы и программы обучения', 'Планы, промежуточные результаты и контрольные точки', 'Порядок по срокам и важности', 'Переход к исходному объекту'],
      sources: [{ label: 'DEV-66122', url: 'https://tracker.yandex.ru/DEV-66122' }],
    },
    {
      id: 'ai-assistant', lane: 'experience', release: 'nov05', title: 'AI-помощник по адаптации',
      outcome: 'Сотрудник быстро понимает, что делать дальше, а руководитель получает сводку по команде и помощь в подготовке целей.',
      status: 'in_progress', progress: 10, owner: 'AI + LMS команды',
      scope: ['Следующие действия сотрудника', 'Сводка по плану', 'Команда, требующая внимания', 'Черновик целей с подтверждением'],
      sources: [{ label: 'DEV-64617', url: 'https://tracker.yandex.ru/DEV-64617' }, { label: 'Проектное решение', url: 'https://docs.google.com/document/d/1FiwFB8ALvGpfbfMpiVs9qy6cHAQZO2umHQk2T6sockA/edit?tab=t.0' }],
    },
    {
      id: 'tenant-copy', lane: 'entry', release: 'nov05', title: 'Коробочный пресет: копирование tenant',
      outcome: 'Суперадминистратор создает новый клиентский tenant из эталонного пресета с готовыми настройками и контентом.',
      status: 'in_progress', progress: 35, owner: 'Платформенная команда',
      scope: ['Эталонный tenant-источник', 'Копирование настроек и сущностей', 'Независимость данных нового клиента', 'Восстановление связей внутри tenant'],
      sources: [{ label: 'DEV-65423', url: 'https://tracker.yandex.ru/DEV-65423' }],
    },
    {
      id: 'self-service', lane: 'entry', release: 'nov05', title: 'Start Self-Service: настройка коробки',
      outcome: 'Клиент самостоятельно выполняет обязательные технические настройки для запуска Skillaz Start.',
      status: 'planned', progress: 5, owner: 'Платформенная команда',
      scope: ['Брендирование страницы авторизации', 'Настройка почтового сервера', 'Настройка способа авторизации'],
      sources: [{ label: 'DEV-65837', url: 'https://tracker.yandex.ru/DEV-65837' }, { label: 'DEV-50301', url: 'https://tracker.yandex.ru/DEV-50301' }],
    },
    {
      id: 'internal-jobs-alerts', lane: 'mobility', release: 'nov05', title: 'Подписки и уведомления о вакансиях',
      outcome: 'Сотрудники подписываются на подходящие вакансии и получают уведомления о новых внутренних возможностях.',
      status: 'planned', progress: 5, owner: 'Команда внутренних переходов',
      scope: ['Подписка по фильтрам', 'Уведомление о новой вакансии', 'Управление подпиской'],
      sources: [{ label: 'DEV-65548', url: 'https://tracker.yandex.ru/DEV-65548' }, { label: 'DEV-65550', url: 'https://tracker.yandex.ru/DEV-65550' }],
    },
  ],
  promo: [
    {
      date: '26 августа 2026', time: '11:00-13:00', title: 'От найма к результату',
      format: 'Открытый экспертный вебинар',
      audience: 'HRD, руководители HR-функций, лидеры адаптации и L&D, HR BP, операционные руководители',
    },
    {
      date: '12-19 октября 2026', title: 'Эффективный вход в новую роль',
      format: 'Открытый обучающий курс',
      audience: 'Руководители HR-функций, специалисты по адаптации и L&D, HR BP, HR-методологи, руководители подразделений',
    },
    {
      date: '19 ноября 2026', title: 'Демо-день Skillaz Старт',
      format: 'Открытый вебинар с демонстрацией продукта',
      audience: 'HRD, лидеры адаптации и L&D, HR BP, руководители подразделений, владельцы HR-tech и цифровых HR-проектов',
    },
    {
      date: '12 декабря 2026', title: 'Эффективный вход в роль для новых руководителей',
      format: 'Открытый практический вебинар',
      audience: 'Новые линейные руководители, кадровый резерв, сотрудники после повышения, HR BP, L&D и команды развития руководителей',
    },
    {
      date: 'Февраль 2027', time: 'Точная дата уточняется', title: 'Внутренний найм и переходы между ролями',
      format: 'Открытый обучающий курс',
      audience: 'HRD, лидеры Talent Management и внутреннего найма, HR BP, L&D, руководители функций и программ кадрового резерва',
    },
    {
      date: '20 февраля 2027', title: 'Демо-день Skillaz Старт',
      format: 'Открытый вебинар с демонстрацией продукта',
      audience: 'HRD, лидеры адаптации, L&D и внутренней мобильности, HR BP, руководители подразделений, владельцы HR-tech-проектов',
    },
    {
      date: '12-19 марта 2027', title: 'Эффективный вход в новую роль',
      format: 'Открытый обучающий курс',
      audience: 'Руководители HR-функций, специалисты по адаптации и L&D, HR BP, HR-методологи, руководители подразделений',
    },
  ],
  methodology: [
    {
      date: '', status: 'done',
      title: 'Методический промпт для ИИ-помощника по целям',
      text: 'Методология формулирования целей с учетом сущностей системы для использования в ИИ-помощнике по целеполаганию.',
    },
    {
      date: 'До 16 октября 2026', status: 'planned',
      title: 'Библиотека универсальных задач на испытательный срок',
      text: '50 шаблонных практических задач по универсальным рабочим активностям.',
    },
    {
      date: 'До 16 октября 2026', status: 'planned',
      title: 'Инструкция и видео для вовлечения руководителя',
      text: 'Текстовая инструкция по целеполаганию и формированию плана от целей, а также видео для размещения в интерфейсе.',
    },
    {
      date: 'До 16 октября 2026', status: 'planned',
      title: 'Сценарии типовых встреч в процессе адаптации',
      text: 'Сценарий первой встречи руководителя и сотрудника и сценарии встреч в контрольных точках.',
    },
    {
      date: 'До 16 октября 2026', status: 'planned',
      title: 'Шаблоны опросов',
      text: 'Опрос для контрольных точек и опрос для подведения итогов адаптации.',
    },
    {
      date: 'До 16 октября 2026', status: 'planned',
      title: 'Инструкция для наставников',
      text: 'Обучающий материал по эффективной работе наставников.',
    },
    {
      date: 'До 16 октября 2026', status: 'planned',
      title: 'Шаблоны welcome-материалов',
      text: 'Welcome book, письма и презентация welcome-тренинга.',
    },
    {
      date: 'До 16 октября 2026', status: 'planned',
      title: 'Методическое пособие по обучению',
      text: 'Инструкции для L&D и HR по созданию эффективных обучающих материалов для адаптации.',
    },
    {
      date: 'До 16 октября 2026', status: 'planned',
      title: 'Лендинг для HR-администраторов',
      text: 'Tilda-лендинг для удобного представления всех методических материалов и рекомендаций в одном месте.',
    },
  ],
  placeholders: [],
};
