const data=window.Q4_DATA;const params=new URLSearchParams(location.search);const clientPage=location.pathname.endsWith('/client.html');const state={mode:clientPage||params.get('view')==='client'?'client':'internal',team:'Умка',module:'Все'};const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
const visibleInitiatives=()=>data.initiatives.filter(item=>state.mode==='client'||item.team===state.team).filter(item=>state.module==='Все'||item.module===state.module).filter(item=>state.mode!=='client'||item.statusKind!=='risk');
function setMode(mode){state.mode=clientPage?'client':mode;state.module='Все';document.body.classList.toggle('client-mode',state.mode==='client');document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));render();if(!clientPage)history.replaceState(null,'',state.mode==='client'?`${location.pathname}?view=client`:location.pathname)}
function renderHero(){const items=visibleInitiatives(),modules=new Set(items.map(x=>x.module));if(state.mode==='client'){$('#heroEyebrow').textContent='Продуктовый план · октябрь — декабрь 2026';$('#heroTitle').textContent='Как развивается Skillaz в четвёртом квартале';$('#heroLead').textContent='Главные изменения по модулям: что появится в продукте и какую задачу бизнеса решает каждая инициатива.'}else{$('#heroEyebrow').textContent='Внутренний роадмап · октябрь — декабрь 2026';$('#heroTitle').textContent='Что команды Skillaz меняют в продукте в четвёртом квартале';$('#heroLead').textContent='Продуктовые инициативы, клиентские обязательства, фактическая загрузка и зоны риска собраны в одном плане.'}const discovery=data.discovery.length;$('#heroMetrics').innerHTML=[[items.length,'инициатив в плане'],[modules.size,'продуктовых модулей'],[discovery,'discovery-треков'],['Q4','горизонт плана']].map(x=>`<div class="hero-metric"><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span></div>`).join('')}
function renderTeams(){const teams=Object.keys(data.teams);$('#teamTabs').innerHTML=teams.map(t=>`<button class="${state.team===t?'active':''}" data-team="${t}">${t}</button>`).join('');document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{state.team=b.dataset.team;state.module='Все';render()});const team=data.teams[state.team];$('#teamMission').textContent=team.mission;$('#teamTitle').textContent=`Команда ${state.team}: ёмкость и готовность`;$('#readiness').innerHTML=`<strong>${team.stats.estimated} из ${team.stats.total}</strong> задач имеют оценку`;const roleLabels={be:'Backend',fe:'Frontend',qa:'QA'};$('#capacityBars').innerHTML=Object.keys(roleLabels).map(role=>{const used=team.effort[role],cap=team.capacity[role],ratio=cap?Math.round(used/cap*100):0;return `<div class="capacity-row ${cap&&used>cap?'over':''}"><span>${roleLabels[role]}</span><div class="capacity-track"><i style="width:${cap?Math.min(100,ratio):100}%"></i></div><small>${used} ч / ${cap?`${cap} ч`:'ёмкость не задана'}</small></div>`}).join('');const s=team.stats;$('#backlogPanel').innerHTML=[[s.product,'продуктовых задач'],[s.client,'клиентских задач'],[s.unestimated,'без оценки'],[s.notReady,'проектных ниже Discovery Research']].map(x=>`<div class="backlog-stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');$('#riskBanner').classList.toggle('visible',Boolean(team.risk));$('#riskBanner').textContent=team.risk}
function renderFilters(){const items=state.mode==='client'?data.initiatives.filter(x=>x.statusKind!=='risk'):data.initiatives.filter(x=>x.team===state.team);const modules=['Все',...new Set(items.map(x=>x.module))];if(!modules.includes(state.module))state.module='Все';$('#moduleFilters').innerHTML=modules.map(m=>`<button class="${state.module===m?'active':''}" data-module="${esc(m)}">${esc(m)}</button>`).join('');document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>{state.module=b.dataset.module;renderHero();renderTimeline();renderFilters()})}
function card(item){const image=item.image?`<div class="initiative-media"><img src="${item.image}" alt="" loading="lazy"></div>`:'<div class="initiative-media no-image"></div>';return `<button class="initiative" data-id="${item.id}">${image}<span class="initiative-body"><span class="initiative-top"><span class="module-tag">${esc(item.module)}</span><span class="status-tag ${item.statusKind||''}">${esc(item.status)}</span></span><h4>${esc(item.title)}</h4><p>${esc(item.value)}</p><span class="initiative-footer"><span class="internal-only">${esc(item.team)}</span><span>Подробнее →</span></span></span></button>`}
function renderTimeline(){const items=visibleInitiatives();$('#roadmapTitle').textContent=state.mode==='client'?'Развитие продукта по модулям':`План поставки команды ${state.team}`;$('#timeline').innerHTML=data.months.map(month=>{const monthItems=items.filter(x=>x.month===month.id);return `<section class="month-column"><header class="month-head"><span>${month.id==='oct'?'01':month.id==='nov'?'02':'03'} · Q4</span><h3>${month.title}</h3><p>${month.note}</p></header><div class="initiative-list">${monthItems.length?monthItems.map(card).join(''):'<div style="padding:28px 16px;color:#71808a;font-size:11px">В выбранном модуле инициатив нет</div>'}</div></section>`}).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openDrawer(b.dataset.id))}
function renderDiscovery(){$('#discoveryGrid').innerHTML=data.discovery.map(item=>`<a class="discovery-card" href="${item.url}" ${item.url==='#'?'':'target="_blank" rel="noreferrer"'}><span>Discovery · Q4</span><h3>${esc(item.title)}</h3><p>${esc(item.value)}</p><small>${esc(item.result)} →</small></a>`).join('')}
function openDrawer(id){const item=data.initiatives.find(x=>x.id===id);if(!item)return;$('#drawerMeta').textContent=`${item.module} · ${data.months.find(x=>x.id===item.month).title}`;$('#drawerTitle').textContent=item.title;$('#drawerValue').textContent=item.value;$('#drawerScope').innerHTML=item.scope.map(x=>`<li>${esc(x)}</li>`).join('');$('#drawerSources').innerHTML=(item.links||[]).map(x=>`<a href="${x[1]}" target="_blank" rel="noreferrer">${esc(x[0])} ↗</a>`).join('');const image=$('#drawerImage');image.classList.toggle('visible',Boolean(item.image));if(item.image){image.src=item.image;image.alt=item.title}else{image.removeAttribute('src');image.alt=''}$('#drawerShell').classList.add('open');$('#drawerShell').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeDrawer(){$('#drawerShell').classList.remove('open');$('#drawerShell').setAttribute('aria-hidden','true');document.body.style.overflow=''}
async function share(){const base=location.pathname.replace(/(?:index|client)\.html$/,'').replace(/\/$/,'');const url=`${location.origin}${base}/client.html`;try{await navigator.clipboard.writeText(url);toast('Ссылка на клиентскую версию скопирована')}catch{prompt('Скопируйте ссылку на клиентскую версию',url)}}
function toast(text){const node=$('#toast');node.textContent=text;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2200)}
function render(){renderHero();if(state.mode==='internal')renderTeams();renderFilters();renderTimeline();renderDiscovery()}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));if($('#shareButton'))$('#shareButton').onclick=share;$('#drawerClose').onclick=closeDrawer;$('#drawerBackdrop').onclick=closeDrawer;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});setMode(state.mode);
